name: Node CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master   

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        install -g @angular/cli
        npm run test ngx-onboarding --watch=false --browsers=ChromeHeadless --code-coverage
        run package
      env:
        CI: true
